### ISSUE TITLE
WiFi Hotspot mode not working

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-sys#101]
- Navigate to http://zynthian.local/api/sys-wifi
- Select "Hotspot" from Mode list
- Click "Save"
Expected behaviour: Hotspot enabled.
Actual behaviour: WiFi On mode selected.

**Comment by jofemodo** [comment]
hostapd & dnsmasq packages were not correctly installed by the setup script.

**Comment by riban-bw** [comment]
This does not seem to be fixed by and update today. I enable WiFi and I see the Zynthian connected to my access point. If I subsequently enable WiFi Hotpot I do not see the Zynthian as an access point using a WiFi monitor on my Android phone and cannot see the network from Ubuntu Mate or Windows laptops. The webconf also behaves the same, i.e. selecting Hotspot results in the webconf showing Wifi on.

During an update I see messages:

sed: can't read /etc/hostapd/hostapd.conf: Not a directory

**Comment by jofemodo** [comment]
It should be fixed, but you have to wait until the new SD image is built, my friend ;-)

**Comment by riban-bw** [comment]
WiFi Hotspot now working.
