### ISSUE TITLE
Add TimGM6mb soundfont

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-sys#109]
The default General MIDI sound font provided with Zynthian is FluidR3_GM.sf2 which is 142MB and takes almost 10s to load. It would be useful to have a smaller GM soundfont that can be loaded quickly.

There is a soundfont called  TimGM6mb.sf2 which is 5.7MB in size and included in the Debian repository as package timgm6mb-soundfont. Many of the sounds within this soundfont are quite good / acceptable and this may provide a lighter alternative.

May I request that timgm6mb-soundfont package be installed and symlink made in the base build to expose this font to Zynthian?

**Comment by jofemodo** [comment]
Done!
