### ISSUE TITLE
bustify update_zynthian.sh 

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-sys#110]
- bash: /zynthian/zynthian-sys/scripts/recipes.update.buster/*.sh: No such file or directory
- Package 'linuxsampler' is not installed, so not removed
E: Unable to locate package libgig6
E: Unable to locate package liblinuxsampler
checking for AUDIOFILE... no
No audio file library found!
Sorry, you need either libsndfile or libaudiofile to compile libgig.
This is needed for the gigextract utility to write audio files.
- src/mod-host.c:39:10: fatal error: readline/readline.h: No such file or directory
 #include <readline/readline.h>
- utils_jack.cpp:23:10: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>
- /zynthian/zyncoder/zyncoder.c:131:16: error: ‘MCP23017_BASE_PIN’ undeclared (first use in this function); did you mean ‘MCP23008_BASE_PIN’?
  mcp23017Setup(MCP23017_BASE_PIN, 0x20);
                ^~~~~~~~~~~~~~~~~
                MCP23008_BASE_PIN
- /zynthian/zyncoder/zyncoder.c:139:36: error: dereferencing pointer to incomplete type ‘struct wiringPiNodeStruct’
  wiringPiI2CWriteReg8(mcp23017_node->fd, MCP23x17_IODIRA, reg);
- /zynthian/zyncoder/zyncoder.c:139:42: error: ‘MCP23x17_IODIRA’ undeclared (first use in this function); did you mean ‘MCP23017_ENCODERS’?
  wiringPiI2CWriteReg8(mcp23017_node->fd, MCP23x17_IODIRA, reg);
and many others

**Comment by jofemodo** [comment]
It should be working on the next "green" nightly build ;-)
