### ISSUE TITLE
install_lv2_lilv.sh does not compile for buster

### ISSUE THREAD

**Issue by lguyome45** [zynthian/zynthian-sys#114]
Hi,
I try to compile ZynthianOs in docker, and lv2_lilv does not compile.
The package 2to3 is missing:

Cloning into 'lilv_python_examples'...
/zynthian/zynthian-sys/scripts/recipes/install_lv2_lilv.sh: line 71: 2to3: command not found
  File "lv2ls.py", line 10
    print plugin.get_uri().as_string()
               ^
SyntaxError: invalid syntax

**Comment by guysoft** [comment]
Its missing python 2to3 binary that converts pytyhon2 code to python 3.,
then tries to run in python3 something that only works in python3

Is a bug that we need to insatll 2to3

**Comment by jofemodo** [comment]
It should work now ;-)
