### ISSUE TITLE
Linuxsampler/libgig/... compiles on every call of update.sh

### ISSUE THREAD

**Issue by dcoredump** [zynthian/zynthian-sys#12]
Call of update.sh after the 2nd call causes every time to build linuxsampler/libgig/... from scratch.

**Comment by jofemodo** [comment]
I can't reproduce this problem in a fresh Gorgona after running "update_zynthian.sh" until been up-to-date.

**Comment by jofemodo** [comment]
OK. I think i found the problem. Please, can you test if it's working now?

**Comment by jofemodo** [comment]
It's not fixed. I solved by installing from scratch (deleting linuxsampler directory).
