### ISSUE TITLE
amsynth not available after install

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-sys#127]
**Describe the bug**
After updating Zynthian to install amsynth I cannot find it. It does not appear in the list of engines nor in the available LV2 plugins in webconf.

**To Reproduce**
Steps to reproduce the behaviour:
1. From webconf perform Update
2. From webconf navigate to Software/LV2-Plugins
3. Select "Advanced View"

**Expected behaviour**
List of available plugins includes amsynth.

**Actual behaviour**
List of available plugins does not include amsynth.

**Setup:**
SD-image
Buster nightly 2019-10-20 updated 2019-11-27

HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ light
Display: Sainsmart 1.8
Wiring: I2C_HWC
GPIO Expander: No detected

SOFTWARE
zyncoder: master (8b7bfbd)
zynthian-ui: master (c02b3ce)
zynthian-sys: master (c16eb29)
zynthian-data: master (d7648f7)
zynthian-webconf: master (813b47d)

**Comment by jofemodo** [comment]
OK! Now webconf will regenerate the list after plugin install,
