### ISSUE TITLE
Hard coded arch CFLAGS in zynthian-sys/scripts/recipes/install_foo-yc20.sh

### ISSUE THREAD

**Issue by TheKikGen** [zynthian/zynthian-sys#143]
I'm currently working to port a subpart of RasPi build scripts to an Asus Tinkerboard.
In zynthian-sys/scripts/recipes/install_foo-yc20.sh (faust),   the arch compilation directives are hard coded despite the fact they are defined at a higher level in zynthian-sys/scripts/zynthian_envars.sh.

zynthian-sys/scripts/recipes/install_foo-yc20.sh
````
if [ ${MACHINE_HW_NAME} = "armv7l" ]; then
	if [[ ${RBPI_VERSION} =~ [2] ]]; then
		export CFLAGS="-O3 -ffast-math -ftree-vectorize -mcpu=cortex-a7 -mtune=cortex-a7 -mfpu=neon-vfpv4 $CFLAGS_UNSAFE"
	else
		export CFLAGS="-O3 -ffast-math -ftree-vectorize -mcpu=cortex-a53 -mtune=cortex-a53 -mfpu=neon-fp-armv8 $CFLAGS_UNSAFE"
	fi
else
	export CFLAGS="-O3 -ffast-math -ftree-vectorize $CFLAGS_UNSAFE"
fi
````
In zynthian-sys/scripts/zynthian_envars.sh

````
if [ "$hw_architecture" = "armv7l" ]; then
	# default is: RPi3
	CPU="-mcpu=cortex-a53 -mtune=cortex-a53"
	FPU="-mfpu=neon-fp-armv8 -mneon-for-64bits"
	if [[ "$rbpi_version" =~ [2] ]]; then
		CPU="-mcpu=cortex-a7 -mtune=cortex-a7"
		FPU="-mfpu=neon-vfpv4"
	fi
````
zynthian-sys/scripts/recipes/install_foo-yc20.sh patched to 
````
CFLAGS+="-O3` -ffast-math -ftree-vectorize $CFLAGS_UNSAFE"
````
, enough to compile.

The Tinkerboard architecture is a 32 Bits arm17-cortex.

**Comment by riban-bw** [comment]
Zynthian will be 64-bit only from oram (next release), supported on Raspberry Pi 3 & 4 (and eventually 5). Any ports to 32-bit platforms will be the respobsibility of the porter. We won't provide any further 32-bit support.
