### ISSUE TITLE
Zynthian permission denied

### ISSUE THREAD

**Issue by benwadub** [zynthian/zynthian-sys#149]
hi, i m new to Zynthian, when I try to login via ssh I get permission denied when using raspberry as password, I can access via webconf but it doesn't ask for login I can t access anything to try Zynthian if someone can help me?

**Comment by jofemodo** [comment]
user: root
password: raspberry

zynthianOS runs everything as root, so only root user is active.

**Comment by benwadub** [comment]
it s what I tried but didn't worked, I did an update on webconf and now I can access on my screen! thanks to tried to help me!

**Comment by jofemodo** [comment]
It must work. What SD image are you using?

**Comment by benwadub** [comment]
I dowloaded this 2019-06-26-zynthianos-stretch-lite-1.0.0-RC3
I still can t acmes to terminal via ssh, don t understand!

**Comment by jofemodo** [comment]
Strange ... it should work ... could you try one of the latest buster builds?

**Comment by benwadub** [comment]
I thought it was the latest! but to be honest I just tried with an cdmi screen, nothing else, maybe it s because of it? I just wanted to try Zynthian to see if I could use it to make an expander without screen, do you think it s possible just to plug a midi controller and audio output? or do I need a screen absolutely? if a screen is needed what could be the cheapest one?

**Comment by jofemodo** [comment]
Hi @benwadub !

Please, this kind of questions are better addressed on the forum:

http://discourse.zynthian.org

BTW, you should connect the zynthian to the network and access with SSH.

Regards

**Comment by benwadub** [comment]
no problem! sorry!
I just tried with the last sd image and I get the same error with ssh with Mac terminal, "permission denied"

**Comment by mheidt** [comment]
Please share screenshots in the forum Tuesday, 24 March 2020, 02:14PM +01:00 from benwadub  notifications@github.com :

**Comment by benwadub** [comment]
![Capture d’écran 2020-03-24 à 15 15 59](https://user-images.githubusercontent.com/59668816/77435535-b41c2000-6de2-11ea-96bc-4d6cdc2c9674.png)


that s what I get when writing my password with ssh in Mac osx terminal; I launched an update with the webconf to see if that permit me to access the ui like yesterday with the older image
thanks for the interest in my problem and sorry for my approximative English I m French

**Comment by mheidt** [comment]
As @jodemodo said...root not zynthian has to be the user Tuesday, 24 March 2020, 03:20PM +01:00 from benwadub  notifications@github.com :

**Comment by benwadub** [comment]
I don t have to connect to Zynthian before login in root?

**Comment by mheidt** [comment]
ssh root@192.... Tuesday, 24 March 2020, 04:16PM +01:00 from benwadub  notifications@github.com :

**Comment by benwadub** [comment]
this is working thanks a lot!!! Zynthian seems to be a real beast!!!
do you know if with this corona story we can order on the Zynthian shop?

**Comment by jofemodo** [comment]
Fantastic!
Regarding your question, you can order on the shop, but i'm not sure of the delivery time, as "Exception State" is declared on Spain. Probably you have to wait 1-2 weeks before we can send your kit.

**Comment by benwadub** [comment]
Thanks, it ll let me time to fix my head hack with my midi din that don’t want to work :-)
