### ISSUE TITLE
Reduce boot time

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-sys#150]
**Is your feature request related to a problem? Please describe.**
The time taken from power on until performance possible is in the order of 30s. This is rather long under normal conditions but painfully slow in a live performance situation. It would be advantageous to substantially reduce the time taken to boot and start the application.

**Describe the solution you'd like**
A boot time from cold boot to available Zynthian (without any engines loaded*) below 10s. (Lower figure would be desirable but 10s seems achievable and probably comparable with other devices.)
*Some engines take significant time to load so should be excluded from this feature request. Individual engine launch / load optimisation should be the subject of a different feature request.

**Describe alternatives you've considered**
There are several methods of reducing the boot time including reducing verbosity of kernel messages, removing some boot delays, altering quantity / order / dependencies of user-space startup applications, improving application start time.

**Additional context**
There are some cold boot delays that may be unavoidable such as detection and reading of boot device. Boot times as low as a few seconds can be achieved but some services may not be available. Some code changes may be required if all services are not available before Zynthian begins, e.g. starting Zynthian before the network is available should be permissible (Zynthian should not have a hard dependency on network) and network support should become available once network is up.

I have done some work on this for other projects which may inform this feature request.

**Comment by jofemodo** [comment]
My crono tells **22 seconds** from power-off to Main menu (no last state saved).

I think you will suffer for going under 15 seconds ... but i really hope you get it!! ;-)
