### ISSUE TITLE
Warning during update

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-sys#153]
**Describe the bug**
Performing an update from webconf shows a warning.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select Update Software in webconf

**Expected behaviour**
Update occurs with no errors or significant warnings.

**Actual behaviour**
A warning is shown in update messages:
```
Executing custom update recipes ...
Executing /zynthian/zynthian-sys/scripts/recipes.update.buster/00_install_packages.sh ...
/zynthian/zynthian-sys/scripts/recipes.update.buster/00_install_packages.sh: line 51: warning: command substitution: ignored null byte in input
```
**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09

OFTWARE
zyncoder: master (3513de2)
zynthian-ui: feature/stepseq (0da9e2a) (this was after update which was performed from master)
zynthian-sys: master (ccad6f8)
zynthian-data: master (9cccef5)
zynthian-webconf: master (ab294aa)

**Additional context**
Not a major issue but we should resolve such warnings. They probably mean something...

**Comment by jofemodo** [comment]
Already known & fixed. See #152.
