### ISSUE TITLE
Transition engines to use KXStudio arm repo

### ISSUE THREAD

**Issue by Baggypants** [zynthian/zynthian-sys#163]
**Is your feature request related to a problem? Please describe.**
engines from KXStudio appear to be more performant. E.g. OB-Xd from KXStudio does not cause xruns on a raspberry pi 3 under the same patch and jack configuration on zynthian compared to the default zynthian compiled plugin. I suspect it's because Falk has enable neon-vfpv4 flags

**Describe the solution you'd like**
New image builds to include and install engines from KXStudio. repo instructions here:
https://kx.studio/Repositories

Add the path `/usr/lib/lv2` to LV2_PATH in zynthian_envars.sh

**Comment by jofemodo** [comment]
And here is the image, succesfully built:

https://os.zynthian.org/2020-07-03-zynthianos-buster-lite-armhf-1.0.0.zip

Although i'm not sure if it's fully functional! We have to test it carefully ...
