### ISSUE TITLE
Zynthian fork of mod-ui is very old

### ISSUE THREAD

**Issue by steveb** [zynthian/zynthian-sys#165]
https://github.com/zynthian/mod-ui is lagging upstream https://github.com/moddevices/mod-ui by about 2 years now. It would be useful to have a branch created which tracks upstream master so we can start applying our customization commits.

Maybe a more conservative approach is needed on the amount and complexity of customizations so that the burden of keeping up with upstream master is lower.

**Comment by guysoft** [comment]
Kind of like #55 which is from two years ago.
It seem like it makes sense to auto-update it rather than needing to open an issue each time for it to update.

**Comment by steveb** [comment]
Actually the series of changes apply fairly cleanly against https://github.com/moddevices/mod-ui, I've posted the branch here https://github.com/steveb/mod-ui/tree/zyn-mod-merge

I haven't tried running it yet
