### ISSUE TITLE
Pianoteq 7.0.1

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-sys#171]
A new Pianotec version is available.
We should change the demo version in the package

**Comment by jofemodo** [comment]
I just update the install script to v6.7.3.
It will be included in next green nightly build for testing.

**Comment by mheidt** [comment]
I am using this one to check in the changes in install_pianoteq_binary.sh

**Comment by mheidt** [comment]
@jofemodo  
We should think about changing pianoteq6 folders to pianoteq. 
When loading a snapshot, we need to be resilient though.

**Comment by jofemodo** [comment]
Totally agree with this ...

**Comment by riban-bw** [comment]
Pianoteq 8 now integrated.
