### ISSUE TITLE
Display information about zynthian during ssh connection

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-sys#178]
**Is your feature request related to a problem? Please describe.**
It can be beneficial to know some information about the build of a Zynthian when you connect via SSH, e.g. its build image, git branches, etc.

**Describe the solution you'd like**
Upon ssh connection Zynthian could display information about itself, e.g.

![image](https://user-images.githubusercontent.com/3158323/94335752-961fba00-ffd5-11ea-8310-c0e0e0610591.png)

**Additional context**
I am not sure what repositories to apply a pull request against so here are the details of how I implemented this:

Within /etc/ssh/sshd_conf add:
```
PrintMotd no
PrintLastLog yes
```
Add file /etc/update-motd.d/00-zynthian:
```
#!/bin/sh

printf " ##########################
#                          #
#            ##            #
#      ##   #  #   ##      #
#     #  #  #  #  #  #     #
###   #  #  #  #  #  #   ###
#  #  #  #  #  #  #  #  #  #
#   ##   #  #  #  #   ##   #
#         ##    ##         #
#                          #
 ##########################
%s
" "$(cat /zynthian/build_info.txt)"
for repo in zyncoder zynthian-ui zynthian-sys zynthian-webconf zynthian-data
do
  branch="$(git -C /zynthian/$repo branch |grep ^* |awk '{print $2}')"
  id="$(git -C /zynthian/$repo rev-parse HEAD | sed 's/\(.\{6\}\).*/\1/')"
  echo "$repo: $branch ($id)"
done
```
`chmod +x /etc/update-motd.d/00-zynthian`

**Comment by jofemodo** [comment]
OK! I did it with some little improvements:

![zynthian_ssh_login_info](https://user-images.githubusercontent.com/834765/95376498-7778c780-08e1-11eb-9ef9-3fe4935af568.png)

Thanks a lot!
