### ISSUE TITLE
noVNC integration

### ISSUE THREAD

**Issue by Baggypants** [zynthian/zynthian-sys#184]
integrate prototype setup described [here](https://discourse.zynthian.org/t/cant-use-vnc/3407/41?u=baggypants) so that a vncserver can be launched in the web config it throws up a html5 vnc client to connect to. Then subsequent engine launches like zynaddsubfx, setBFree et al can have the gui displayed in a browser.

**Comment by jofemodo** [comment]
Hi @Baggypants, @wyleu  and others!

I just added noVNC integration. It's enabled from UI's admin (VNC Server) or webconf (UI options). Once it's enabled, you can access noVNC on:

http://zynthian.local:6080

also, a link is available from webconf's software menu. Please, update and test.

Enjoy ... and thanks for clearing the way!!
