### ISSUE TITLE
Critical: Software update modifies / corrupts .vnc/passwd

### ISSUE THREAD

**Issue by mark-orion** [zynthian/zynthian-sys#186]
**Describe the bug**
Whenever the software update is run, any existing VNC configuration becomes unusable because the password file .vnc/passwd is modified and any existing authorization credentials are lost. I consider this critical as a remotely controlled system becomes unusable. 

**To Reproduce**
login via ssh and check the modification time of .vnc/passwd
run software update
the file has changed

**Expected behavior**
any existing .vnc/passwd should not be touched.

**Comment by jofemodo** [comment]
It should be fixed now. Please, update and test.

**Comment by mark-orion** [comment]
I can confirm that the problem is gone. Thanks for fixing this so quickly.
