### ISSUE TITLE
Panel to manage windows in VNC display

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-sys#192]
**Is your feature request related to a problem? Please describe.**
In the VNC extended display the windows are managed by xfce window manager. This provides window decoration and other window management elements. It may be advantageous to be able to launch applications and see what is running.

**Describe the solution you'd like**
A panel (task bar) displayed in VNC viewer which allows launching of applications, e.g. patchage and control and monitoring of running applications.

**Describe alternatives you've considered**
A panel or dock which shows the avialable applications and allows starting and focusing them.

**Additional context**
I have worked up an example using xfce4-panel which has a panel at the top of the screen. The panel has a combined desktop switcher / appliation selector drop down, launch buttons for each of the required applications (patchage and terminal), indications of running applications and a clock. I wrote a helper script which only launches an application is it is not already running so that the launcher buttons can be used without triggering lots of instances of applications.

![image](https://user-images.githubusercontent.com/3158323/111888322-5a3d3e80-89d3-11eb-8603-18970500c63f.png)

**Comment by riban-bw** [comment]
Oops! I'm not completely happy with this implementation. I was considering changing the panel to be smaller hence I wanted to do more testing hence delay before PR. Maybe we should be more stringent on the workflow, requiring a PR before any merges take place to avoid partial developments being merged too early.

**Comment by jofemodo** [comment]
You are right. No more merges without a PR ;-)
For this case, i would like to see improved the "look and feel" of launcher buttons. They are really ugly. In fact we should try to keep a coherent style on all zynthian interfaces.

Thanks!

**Comment by riban-bw** [comment]
One of these days I might take offence at you describing my work as "ugly" :wink: .

I looked at various docks but couldn't get any to work. I observe the choice of xfce4 as the window manager so used the xfce4 panel. I could not find a combined launcher and running app manager plugin so effectively wrote one by calling a helper script to launch apps. In practice we only need to launch a couple:

- Patchage
- Terminal

Other running apps are engines launched by Zynthian. I added the desktop / app widget which:

- Is small
- Indicates the currently focused app
- Allows focusing of an app
- Allows moving apps between desktops
- Some other features

I quite like this because it means we could lose the currently running app widget and collapse down to a smaller panel. We could use icons for the launchers and recover most of the top line of the screen.

**Comment by jofemodo** [comment]
Ohhh! Please, don't do that! Your work is beautiful, but the launcher buttons are ugly. It's not your fault, it's the buttons fault.
I'm pretty sure we can add some decoration to this buttons and convert the ugly into beauty.

BTW, I would remove these elements:

+ clock (a cpu/memory monitor will be more useful)
+ "window manager" buttton
+ "panel config" button

We only need the "patchage" and the "terminal" buttons. Less is more ;-)

Thanks!

**Comment by riban-bw** [comment]
Yep! Those were on my list for the chop. I think just the pull-down window manager so that users can access hidden apps and Lainey's for Patchage and terminal. We could also use icons instead of words for the launcher buttons which may be less ugly. I will have a look.

**Comment by riban-bw** [comment]
Things may not have gotten much less _ugly_ but it is working fine so closing this ticket.
