### ISSUE TITLE
Selecting Pianoteq LV2 preset seems to give random settings

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-sys#198]
**Describe the bug**
The first time you select a Pianoteq LV2 preset the sound is all wrong. Selecting a different preset of the same instrument corrects the problem.

**To Reproduce**
1. Add Pianoteq LV2 layer
2. Select an instrument and preset
3. Play note

**Expected behaviour**
Pianoteq note plays as expeted.

**Actual behaviour**
Pianoteq note plays with some odd muting, repeated hammering and reverb.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 24% (475M/1939M)
SD Card: 38% (10G/28G)
Temperature: 48.0ºC

SOFTWARE
zyncoder: master (3c914fe)
zynthian-ui: master (84a7f25)
zynthian-sys: master (348f40c)
zynthian-data: master (194fd59)
zynthian-webconf: master (c8cd1a6)

**Screenshots**
![image](https://user-images.githubusercontent.com/3158323/111075910-01a50780-84e2-11eb-8914-b53bdef6a065.png)
![image](https://user-images.githubusercontent.com/3158323/111075930-0f5a8d00-84e2-11eb-9a2f-4bf6f8ef8826.png)

**Additional context**
It seems like the LV2 gets random settings (or maybe not random but wrong) when a new instrument is loaded. Selecting a different preset fixes it but selecting and another instrument pack breaks it again.

**Comment by jofemodo** [comment]
The problem is related with the way jalv save the presets. I have solved the issue by using the new self-generating options from pianoteq CLI, available from version 7.2.1. I also fixed a bug on jalv and removed from zynthian-data the jalv-generated presets for Pianoteq 7.
