### ISSUE TITLE
Version release numbering

### ISSUE THREAD

**Issue by guysoft** [zynthian/zynthian-sys#44]
Hey,
So CustomPiOS tends to assume you have a version number, as specified in: https://github.com/guysoft/ZynthianOS/blob/devel/src/config#L2

What should I put in it for ZynthianOS? It gets appended to the image name and is stored in ``/etc/zynthianos_version``, helps users know what version they have.

**Comment by jofemodo** [comment]
I think we should start with version 1.0 and consider previous "Gorgona" releases as 0.x ;-)
So, we are working for ZynthianOS v1.0 ...

**Comment by guysoft** [comment]
I am making it V1.0.0 , so we have a minor for bug fixes.

**Comment by jofemodo** [comment]
Perfect. I suposse every "night build" doesn't increase this number. It should be something like ZynthianOS v1.0.0 build-20180326 ... am i right?

**Comment by guysoft** [comment]
No, 
The version is part of the build, so what Jenkins does is renames the zip to include the build date, that way you can release a nightly as a release candidate and eventually a release. You don't want to rebuild especially for a release,  defies the point.

**Comment by jofemodo** [comment]
Oko. Understand. It seems good to me ;-)
