### ISSUE TITLE
Old .img filename date inside new zip filename on os.zynthian.org

### ISSUE THREAD

**Issue by hammerandtongs** [zynthian/zynthian-sys#66]
Is the build process correct?

Example - 

2018-**08-06**_2018-06-27-zynthianos-stretch-lite-1.0.0.zip

contained

2018-**06-27**-zynthianos-stretch-lite-1.0.0.img

**Comment by guysoft** [comment]
Yes,
the first date is the date of the build, the second date is from the original base-image file by raspbian. It tells us which base image was used.

The reason the nightly build date does not appear in the extracted file is because when a stable release is made you want to remove the build date without extracting and compressing the file.

**Comment by mheidt** [comment]
But is it possible to create a build label.txt that contains the daily label?

**Comment by guysoft** [comment]
It is, but users rarely post that when they report bugs. Asking "what is the file name" seems to work better.

I think we should have both. But didn't get to adding it in CustomPiOS

**Comment by jofemodo** [comment]
Hi @guysoft!

But having the raspbian base image in the img file can be confusing too.

We could use "sed" for replacing the filename by a different one of the same size:

`sed -i 's/2018-10-09-zynthianos-stretch-lite-1.0.0.img/2019-02-27-zynthianos-stretch-lite-1.0.0.img/g' 2019-02-27_2018-10-09-zynthianos-stretch-lite-1.0.0.zip
`
;-)

I've changed the ZynthianOS jenkins script for using building date for zip and img filenames.
When we release an official build, if it's convenient, we can replace the date part by some fixed-size string (10 chars). For instance, we could start with "2019-aruki", that contains the year and release name ;-)

**Comment by guysoft** [comment]
I could also add a setting in CustomPiOS, when I get to it

**Comment by jofemodo** [comment]
This will be better, of course, specially if we can avoid the "sed" for changing the filename, that is quite heavy for a 4GB file ;-)

**Comment by guysoft** [comment]
Renaming and zipping happens here in the ``release`` script:

https://github.com/guysoft/CustomPiOS/blob/devel/src/release#L16

It sources the config scripts. So we could set a ``DIST_IMG_FILENAME`` and if its defined and is not empty set it instead of ``${FILENAME::-4}``

**Comment by jofemodo** [comment]
OK! It seems OK to me!

**Comment by guysoft** [comment]
Ok, I added a new option for this in CustomPiOS. If you wanna use it: https://github.com/guysoft/CustomPiOS/issues/45#issuecomment-574164161
