### ISSUE TITLE
CAPS AmpVTS - No Sound

### ISSUE THREAD

**Issue by rodamaralgeo** [zynthian/zynthian-sys#67]
Hi guys, 

I am using [the last image of the system](http://os.zynthian.org/2018-08-06_2018-06-27-zynthianos-stretch-lite-1.0.0.zip), and when using MOD-UI with the CAPS AmpVTS plugin I have no sound.

When the plugin is in the baypassed (turned off)  the sound is played correctly.

**Comment by jofemodo** [comment]
Could you re-check if it's working now?

**Comment by rodamaralgeo** [comment]
Works Fine!
