### ISSUE TITLE
Failed to install pexpect

### ISSUE THREAD

**Issue by rodamaralgeo** [zynthian/zynthian-sys#71]
Hi Guys!

After updating my Zynthian, the startup displays an error message.
When I tried to restart zynthian in debug mode, I noticed that pexpect was not installed.
When I try to install, I get the following error:
![image](https://user-images.githubusercontent.com/28227717/46248424-91789900-c3ef-11e8-9c39-995bffe1ce24.png)

**Comment by mheidt** [comment]
Are you sure, that the update didn't break your WiFi? Connected via ethernet?
Looks like a internet connectivity issue to me

**Comment by jofemodo** [comment]
Zynthian uses "htpdate" for time sync. It's loaded on every boot and remains as a daemon, so it shouldn't be needed to fix the time or do anything related.
