### ISSUE TITLE
DPF-Plugins build breaks

### ISSUE THREAD

**Issue by guysoft** [zynthian/zynthian-sys#74]
```
# ProM (needs OpenGL + ProjectM)
```

And later:
```
cp -r bin/ProM             /usr/local/bin/
/bin/cp: cannot stat 'bin/ProM': No such file or directory
Makefile:114: recipe for target 'install' failed
```

Source:
https://github.com/DISTRHO/DPF-Plugins/blob/master/Makefile#L48

Full log:
http://os.zynthian.org:8080/job/ZynthianOS/208/parsed_console/job/ZynthianOS/208/parsed_console/log_content.html#WARNING1

Build script: https://github.com/zynthian/zynthian-sys/blob/master/scripts/recipes/install_dpf_plugins.sh

**Comment by jofemodo** [comment]
It should work fine now ;-)

**Comment by guysoft** [comment]
Yay, issue also fixed at: https://github.com/DISTRHO/DPF-Plugins/issues/10

**Comment by jofemodo** [comment]
Nice! ;-)
We are really close ... latest images are working quite well and i hope to release a new official SD image based in ZynthianOS in the next weeks.
