### ISSUE TITLE
Bunch of builds fail on lo/lo.h and fftw3.h: No such file or directory a

### ISSUE THREAD

**Issue by guysoft** [zynthian/zynthian-sys#75]
lo/lo.h: No such file or directory

error: fftw3.h: No such file or directory
 #include <fftw3.h>

http://os.zynthian.org:8080/job/ZynthianOS/213/parsed_console/

**Comment by guysoft** [comment]
Looks better, saw also

```
../src/cocoa_in_qt5.mm:17:24: fatal error: Cocoa/Cocoa.h: No such file or directory
```

**Comment by guysoft** [comment]
Unrelated but:
```
./setup_plugins_rbpi.sh: line 47: /zynthian/zynthian-sys/scripts/recipes/install-calf.sh: No such file or directory
```

**Comment by guysoft** [comment]
Also
```
21:02:08 /usr/bin/touch: missing file operand
21:02:08 Try '/usr/bin/touch --help' for more information.
21:02:09 fatal: Not a git repository (or any of the parent directories): .git
21:02:09 Copying default Aeolus Waves ...
21:02:09 /zynthian/zynthian-sys/scripts/update_zynthian_sys.sh: line 232: cd: /usr/share/aeolus/stops: No such file or directory
```

**Comment by jofemodo** [comment]
Hi @guysoft !

I'm working on it and i hope to upload the fixes before this night. Anyway, i've seen this error:

`Failed to connect to bus: No such file or directory`

when calling systemctl. Do you know if we can call systemctl from inside the container or we should be using a different way?

Thanks!

**Comment by guysoft** [comment]
In general its a bad idea to run systemd inside the chroot because you are not running a full system, only a chroot jail. The system never booted.
It means you need stuff like ``/proc`` mounted which is shared with the host, and is dependent on it.

You can google and see similar arguments why not o use systemd in docker, because what we are doing is a kind of container.

I would suggest, since I can see systemd is part of your scripts add an environment variable that skips the systemd commands. Or alternatively use a bash alias to override what the commend systemd does.
 
Anyway, I see the builds are green now :+1:
