### ISSUE TITLE
Strange size variations in built images

### ISSUE THREAD

**Issue by jofemodo** [zynthian/zynthian-sys#76]
Observing the list in:

http://os.zynthian.org/

There are strange variations in the image size. It should be very similar, given that build status is green.

Am i missing something?

**Comment by guysoft** [comment]
It could jump few tens of megabytes in OctoPi, which is 500MB total.  I would guess ~100 might be. The 500MB you see is strange.  You can open the .img file,  mount it and run a folder -level diff.

**Comment by guysoft** [comment]
Looks like a healthy build is 4.3 GB

**Comment by guysoft** [comment]
Still large jumps.
It might just be luck.

**Comment by jofemodo** [comment]
It seems like some process is failing randomly and parsed log doesn't detect it. A log diff could help. I will try it ....

**Comment by guysoft** [comment]
Please add to the log parsing anything that needs to be detected, the list is at:
``/home/guysoft/CustomPiOS/src/misc/jenkins-ci/console_parsing``

**Comment by jofemodo** [comment]
Ups!! I spend 1 hour inspecting the log diff and i can't find any relevant difference. It's a kind of magic!!
Do you have some idea? It's quite strange ...

I will try to burn the same both images that i compared for doing a functional test to see if i can detect some difference ...

Regards,

**Comment by guysoft** [comment]
If the log is the same then it seems like its just random.
Test images regardless.

**Comment by jofemodo** [comment]
Latest builds have similar sizes. "Problem"  seems to be solved by itself ...
