### ISSUE TITLE
Add -10dB pad into Audio config 

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-sys#79]
Add -10dB pad into Audio config to allow for high volume playing without clipping.

**Comment by guysoft** [comment]
Er - I am not sure I understand what this means, can you explain what you are trying to do, with what hardware?
Or perhaps @jofemodo might understand what this is.

**Comment by wyleu** [comment]
Add  function that can effectively turn down the overall volume by a specific amount to allow hi volume signals to be played at a 'decent' level. A +10dB pad could also be added to boost low level signals.

From the Nord Modular G2 external input module from the manual...

![image](https://user-images.githubusercontent.com/79083/52809506-5918e500-3088-11e9-862b-608b608c5c37.png)

**Comment by guysoft** [comment]
Ok, why not use an lv2 plugin?
(Just trying to.understand why this is a general function)

**Comment by wyleu** [comment]
It's an overall characteristic at the periphery of the jack infrastructure
rather than a component within a particular engine.

**Comment by wyleu** [comment]
It's an upshot of the forum thread.
https://discourse.zynthian.org/t/issue-volume-output-too-high-producing-clipping-like-noise/2718/20

Should it be applied to each engine at part of it's initialization.

**Comment by jofemodo** [comment]
This should be implemented in the "mixer". BTW we should have an open task for discussing mixer features and implementation.

**Comment by riban-bw** [comment]
I am closing this ticket as we now have individual control of each chain and the main mixbus in the mixer as well as more flexible processor / plugin management. If you (@wyleu) still feel stongly there is benefit for a pad in the chain then please raise new ticket in the issue tracker.
