### ISSUE TITLE
vi and tabs

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-sys#87]
could we add this in a file ~/.vimrc

set softtabstop=0 noexpandtab

Suddenly I couldn't change files with vi anymore correctly. Tabs were changed to spaces.

**Comment by mheidt** [comment]
And I don't want to change this file with every new os build :)

**Comment by riban-bw** [comment]
Yes please! Vim in Aruk is driving me up the wall. I can't enter tabs and I can't highlight and copy text. I have to use nano, blurk!!!

**Comment by jofemodo** [comment]
I've added a global "vimrc.local" to /etc/vim. Please, confirm that this solves your problems ;-)

**Comment by mheidt** [comment]
The file is missing in the latest buster image

**Comment by jofemodo** [comment]
Curious ... the file is on the repo:

https://github.com/zynthian/zynthian-sys/tree/master/etc/vim

And it's been copied ...

https://github.com/zynthian/zynthian-sys/blob/fb5e4544c088c31afffbfb43da43af7032d10fcb/scripts/update_zynthian_sys.sh#L267

I will take a look ...

**Comment by mheidt** [comment]
But ~/.vimrc still not there

**Comment by jofemodo** [comment]
Try updating now ;-)
