### ISSUE TITLE
USB Mouse not recognised 

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-sys#88]
A USB mouse no longer operates the zynthian GUI.

Zynth Audio Enjector,ALL-In-Ine X , HDMI

Without Mouse.
lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/5p, 12M
        |__ Port 1: Dev 3, If 0, Class=Vendor Specific Class, Driver=smsc95xx, 12M

With Mouse

lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/5p, 12M
        |__ Port 1: Dev 3, If 0, Class=Vendor Specific Class, Driver=smsc95xx, 12M

WITH MOUSE & AKAI Keyboard....
lsusb -t
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/5p, 12M
        |__ Port 1: Dev 3, If 0, Class=Vendor Specific Class, Driver=smsc95xx, 12M
        |__ Port 2: Dev 9, If 0, Class=Human Interface Device, Driver=usbhid, 12M
        |__ Port 2: Dev 9, If 1, Class=Audio, Driver=snd-usb-audio, 12M
        |__ Port 2: Dev 9, If 2, Class=Audio, Driver=snd-usb-audio, 12M

**Comment by guysoft** [comment]
Ouptut of ``dmesg``?

**Comment by wyleu** [comment]
dmesg:-
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.18.7-v7+ (matuschd@storage) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03)) #1 SMP Fri Sep 14 08:48:48 CEST 2018
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 3 Model B Rev 1.2
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 8 MiB at 0x3ac00000
[    0.000000] On node 0 totalpages: 242688
[    0.000000]   Normal zone: 2133 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 242688 pages, LIFO batch:31
[    0.000000] random: get_random_bytes called from start_kernel+0x7c/0x490 with crng_init=0
[    0.000000] percpu: Embedded 17 pages/cpu @(ptrval) s39104 r8192 d22336 u69632
[    0.000000] pcpu-alloc: s39104 r8192 d22336 u69632 alloc=17*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 240555
[    0.000000] Kernel command line: 8250.nr_uarts=1 bcm2708_fb.fbwidth=1280 bcm2708_fb.fbheight=1024 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.speed=1 dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 940124K/970752K available (7168K kernel code, 623K rwdata, 2144K rodata, 1024K init, 820K bss, 22436K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xbb800000 - 0xff800000   (1088 MB)
                   lowmem  : 0x80000000 - 0xbb400000   ( 948 MB)
                   modules : 0x7f000000 - 0x80000000   (  16 MB)
                     .text : 0x(ptrval) - 0x(ptrval)   (8160 kB)
                     .init : 0x(ptrval) - 0x(ptrval)   (1024 kB)
                     .data : 0x(ptrval) - 0x(ptrval)   ( 624 kB)
                      .bss : 0x(ptrval) - 0x(ptrval)   ( 821 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 26013 entries in 77 pages
[    0.000000] Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000003] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000012] Switching to timer-based delay loop, resolution 52ns
[    0.000156] Console: colour dummy device 80x30
[    0.000433] console [tty1] enabled
[    0.000455] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.000476] pid_max: default: 32768 minimum: 301
[    0.000666] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000684] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.001304] Disabling memory control group subsystem
[    0.001358] CPU: Testing write buffer coherency: ok
[    0.001640] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.001990] Setting up static identity map for 0x100000 - 0x10003c
[    0.002079] Hierarchical SRCU implementation.
[    0.002517] smp: Bringing up secondary CPUs ...
[    0.003031] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.003566] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.004058] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.004117] smp: Brought up 1 node, 4 CPUs
[    0.004155] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.004166] CPU: All CPU(s) started in HYP mode.
[    0.004176] CPU: Virtualization extensions available.
[    0.004722] devtmpfs: initialized
[    0.010506] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.010659] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.010683] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.011029] pinctrl core: initialized pinctrl subsystem
[    0.011515] NET: Registered protocol family 16
[    0.012661] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.015450] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.015466] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.015593] Serial: AMBA PL011 UART driver
[    0.016669] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.016931] uart-pl011 3f201000.serial: could not find pctldev for node /soc/gpio@7e200000/uart0_pins, deferring probe
[    0.034422] bcm2835-dma 3f007000.dma: DMA legacy API manager at (ptrval), dmachans=0x1
[    0.035256] SCSI subsystem initialized
[    0.035382] usbcore: registered new interface driver usbfs
[    0.035419] usbcore: registered new interface driver hub
[    0.035462] usbcore: registered new device driver usb
[    0.040046] raspberrypi-firmware soc:firmware: Attached to firmware from 2019-02-12 19:42
[    0.040813] clocksource: Switched to clocksource arch_sys_counter
[    0.083665] VFS: Disk quotas dquot_6.6.0
[    0.083728] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.083864] FS-Cache: Loaded
[    0.083998] CacheFiles: Loaded
[    0.088784] NET: Registered protocol family 2
[    0.089206] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes)
[    0.089239] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.089304] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.089405] TCP: Hash tables configured (established 8192 bind 8192)
[    0.089492] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.089525] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.089678] NET: Registered protocol family 1
[    0.090019] RPC: Registered named UNIX socket transport module.
[    0.090032] RPC: Registered udp transport module.
[    0.090042] RPC: Registered tcp transport module.
[    0.090052] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.090992] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.092604] Initialise system trusted keyrings
[    0.092732] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.097583] FS-Cache: Netfs 'nfs' registered for caching
[    0.097935] NFS: Registering the id_resolver key type
[    0.097964] Key type id_resolver registered
[    0.097974] Key type id_legacy registered
[    0.097990] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.099156] Key type asymmetric registered
[    0.099170] Asymmetric key parser 'x509' registered
[    0.099216] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 250)
[    0.099307] io scheduler noop registered
[    0.099318] io scheduler deadline registered (default)
[    0.099476] io scheduler cfq registered
[    0.099488] io scheduler mq-deadline registered (default)
[    0.099499] io scheduler kyber registered
[    0.101018] BCM2708FB: allocated DMA memory fac50000
[    0.101048] BCM2708FB: allocated DMA channel 0 @ (ptrval)
[    0.123540] Console: switching to colour frame buffer device 160x64
[    0.134815] Serial: 8250/16550 driver, 1 ports, IRQ sharing enabled
[    0.135760] bcm2835-rng 3f104000.rng: hwrng registered
[    0.135924] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.136315] vc-sm: Videocore shared memory driver
[    0.136539] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    0.142120] brd: module loaded
[    0.147581] loop: module loaded
[    0.147659] Loading iSCSI transport class v2.0-870.
[    0.148161] libphy: Fixed MDIO Bus: probed
[    0.148289] usbcore: registered new interface driver lan78xx
[    0.148400] usbcore: registered new interface driver smsc95xx
[    0.148492] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.376423] Core Release: 2.80a
[    0.376480] Setting default values for core params
[    0.376571] Finished setting default values for core params
[    0.576811] Using Buffer DMA mode
[    0.576867] Periodic Transfer Interrupt Enhancement - disabled
[    0.576952] Multiprocessor Interrupt Enhancement - disabled
[    0.577034] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.577103] Dedicated Tx FIFOs mode
[    0.577395] WARN::dwc_otg_hcd_init:1046: FIQ DMA bounce buffers: virt = 0xbac44000 dma = 0xfac44000 len=9024
[    0.577546] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    0.577850] dwc_otg: Microframe scheduler enabled
[    0.577874] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x805ff5e4
[    0.577964] WARN::hcd_init_fiq:460: FIQ ASM at 0x805ff938 length 36
[    0.578058] WARN::hcd_init_fiq:486: MPHI regs_base at 0xbb87e000
[    0.581621] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.585124] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.588649] dwc_otg 3f980000.usb: irq 56, io mem 0x00000000
[    0.592147] Init: Port Power? op_state=1
[    0.595596] Init: Power Port (0)
[    0.599134] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.18
[    0.602674] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.606245] usb usb1: Product: DWC OTG Controller
[    0.609788] usb usb1: Manufacturer: Linux 4.18.7-v7+ dwc_otg_hcd
[    0.613354] usb usb1: SerialNumber: 3f980000.usb
[    0.617196] hub 1-0:1.0: USB hub found
[    0.620703] hub 1-0:1.0: 1 port detected
[    0.624473] dwc_otg: FIQ enabled
[    0.624476] dwc_otg: NAK holdoff enabled
[    0.624479] dwc_otg: FIQ split-transaction FSM enabled
[    0.624486] Module dwc_common_port init
[    0.624635] usbcore: registered new interface driver usb-storage
[    0.628179] mousedev: PS/2 mouse device common for all mice
[    0.632132] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.635809] bcm2835-cpufreq: min=1200000 max=1200000
[    0.639569] sdhci: Secure Digital Host Controller Interface driver
[    0.643107] sdhci: Copyright(c) Pierre Ossman
[    0.646825] mmc-bcm2835 3f300000.mmc: could not get clk, deferring probe
[    0.650565] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    0.654203] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.658069] ledtrig-cpu: registered to indicate activity on CPUs
[    0.661656] hidraw: raw HID events driver (C) Jiri Kosina
[    0.665317] usbcore: registered new interface driver usbhid
[    0.668913] usbhid: USB HID core driver
[    0.672917] vchiq: vchiq_init_state: slot_zero = (ptrval), is_master = 0
[    0.677632] [vc_sm_connected_init]: start
[    0.685373] [vc_sm_connected_init]: end - returning 0
[    0.689478] Initializing XFRM netlink socket
[    0.693122] NET: Registered protocol family 17
[    0.696796] Key type dns_resolver registered
[    0.700590] Registering SWP/SWPB emulation handler
[    0.704488] registered taskstats version 1
[    0.707996] Loading compiled-in X.509 certificates
[    0.715123] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.718685] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    0.723199] 3f215040.serial: ttyS0 at MMIO 0x0 (irq = 53, base_baud = 50000000) is a 16550
[    0.727319] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    0.730969] mmc-bcm2835 3f300000.mmc: DMA channel allocated
[    0.760323] sdhost: log_buf @ (ptrval) (fac47000)
[    0.799421] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.804586] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.809675] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.813254] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.837971] of_cfs_init
[    0.839237] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.841590] of_cfs_init: OK
[    0.845136] Indeed it is in host mode hprt0 = 00021501
[    0.852235] Waiting for root device /dev/mmcblk0p2...
[    0.953080] random: fast init done
[    0.973850] mmc0: host does not support reading read-only switch, assuming write-enable
[    0.980850] mmc0: new high speed SDHC card at address aaaa
[    0.984987] mmcblk0: mmc0:aaaa SC32G 29.7 GiB
[    0.993161]  mmcblk0: p1 p2
[    1.012927] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    1.016599] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.018959] mmc1: new high speed SDIO card at address 0001
[    1.027703] devtmpfs: mounted
[    1.034686] Freeing unused kernel memory: 1024K
[    1.060837] usb 1-1: new full-speed USB device number 2 using dwc_otg
[    1.064614] Indeed it is in host mode hprt0 = 00021501
[    1.301018] usb 1-1: not running at top speed; connect to a high speed hub
[    1.304961] usb 1-1: New USB device found, idVendor=0424, idProduct=9514, bcdDevice= 2.00
[    1.308729] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.312916] hub 1-1:1.0: USB hub found
[    1.316712] hub 1-1:1.0: 5 ports detected
[    1.551491] systemd[1]: System time before build time, advancing clock.
[    1.640854] usb 1-1.1: new full-speed USB device number 3 using dwc_otg
[    1.656442] NET: Registered protocol family 10
[    1.660866] Segment Routing with IPv6
[    1.695182] random: systemd: uninitialized urandom read (16 bytes read)
[    1.702172] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    1.710367] systemd[1]: Detected architecture arm.
[    1.745898] systemd[1]: Set hostname to <zynthian-nord>.
[    1.771049] usb 1-1.1: not running at top speed; connect to a high speed hub
[    1.775443] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00, bcdDevice= 2.00
[    1.779428] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.784378] random: systemd: uninitialized urandom read (16 bytes read)
[    1.787309] smsc95xx v1.0.6
[    1.794577] random: systemd-cryptse: uninitialized urandom read (16 bytes read)
[    1.904100] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:c7:cb:be
[    2.000870] usb 1-1.2: new full-speed USB device number 4 using dwc_otg
[    2.131781] usb 1-1.2: New USB device found, idVendor=2011, idProduct=0715, bcdDevice= 0.00
[    2.136025] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.140228] usb 1-1.2: Product: MPKmini2
[    2.144422] usb 1-1.2: Manufacturer: AKAI
[    2.148597] usb 1-1.2: SerialNumber: 0001
[    2.154975] hid-generic 0003:2011:0715.0001: hiddev96,hidraw0: USB HID v1.11 Device [AKAI MPKmini2] on usb-3f980000.usb-1.2/input0
[    2.237571] systemd[1]: Listening on udev Kernel Socket.
[    2.247101] systemd[1]: Reached target Swap.
[    2.250845] usb 1-1.5: new low-speed USB device number 5 using dwc_otg
[    2.260381] systemd[1]: Listening on fsck to fsckd communication Socket.
[    2.269640] systemd[1]: Listening on Journal Socket (/dev/log).
[    2.279108] systemd[1]: Listening on Journal Socket.
[    2.288941] systemd[1]: Created slice User and Session Slice.
[    2.298904] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    2.430765] i2c /dev entries driver
[    2.790877] usb 1-1.5: new low-speed USB device number 6 using dwc_otg
[    2.810264] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    2.888647] systemd-journald[109]: Received request to flush runtime journal from PID 1
[    3.210002] audioinjector-stereo soc:sound: ASoC: CPU DAI (null) not registered - will retry
[    3.210014] audioinjector-stereo soc:sound: snd_soc_register_card failed (-517)
[    3.212900] audioinjector-stereo soc:sound: ASoC: CODEC DAI wm8731-hifi not registered - will retry
[    3.212914] audioinjector-stereo soc:sound: snd_soc_register_card failed (-517)
[    3.231089] usb 1-1-port5: attempt power cycle
[    3.336009] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    3.354736] audioinjector-stereo soc:sound: ASoC: CODEC DAI wm8731-hifi not registered - will retry
[    3.354750] audioinjector-stereo soc:sound: snd_soc_register_card failed (-517)
[    3.355698] audioinjector-stereo soc:sound: ASoC: CODEC DAI wm8731-hifi not registered - will retry
[    3.355711] audioinjector-stereo soc:sound: snd_soc_register_card failed (-517)
[    3.365582] wm8731 1-001a: Assuming static MCLK
[    3.365604] wm8731 1-001a: 1-001a supply AVDD not found, using dummy regulator
[    3.365675] wm8731 1-001a: 1-001a supply HPVDD not found, using dummy regulator
[    3.365706] wm8731 1-001a: 1-001a supply DCVDD not found, using dummy regulator
[    3.365744] wm8731 1-001a: 1-001a supply DBVDD not found, using dummy regulator
[    3.376314] audioinjector-stereo soc:sound: wm8731-hifi <-> 3f203000.i2s mapping ok
[    3.406173] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    3.419564] usbcore: registered new interface driver snd-usb-audio
[    3.459619] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    3.463422] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[    3.463595] usbcore: registered new interface driver brcmfmac
[    3.673355] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[    3.673415] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[    3.673954] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Oct 23 2017 03:55:53 version 7.45.98.38 (r674442 CY) FWID 01-e58d219f
[    3.890902] usb 1-1.5: new low-speed USB device number 7 using dwc_otg
[    3.983012] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[    3.983163] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    4.345013] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[    4.345032] brcmfmac: power management disabled
[    4.430886] usb 1-1.5: new low-speed USB device number 8 using dwc_otg
[    5.052712] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[    5.655000] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    5.655950] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xC5E1
[    5.928959] bcm2835-i2s 3f203000.i2s: I2S SYNC error!
[    6.332249] uart-pl011 3f201000.serial: no DMA platform data
[    8.751508] Bluetooth: Core ver 2.22
[    8.751588] NET: Registered protocol family 31
[    8.751591] Bluetooth: HCI device and connection manager initialized
[    8.751609] Bluetooth: HCI socket layer initialized
[    8.751618] Bluetooth: L2CAP socket layer initialized
[    8.751641] Bluetooth: SCO socket layer initialized
[    8.766583] Bluetooth: HCI UART driver ver 2.3
[    8.766597] Bluetooth: HCI UART protocol H4 registered
[    8.766602] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    8.766914] Bluetooth: HCI UART protocol Broadcom registered
[    9.067633] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    9.067642] Bluetooth: BNEP filters: protocol multicast
[    9.067660] Bluetooth: BNEP socket layer initialized
[   10.075873] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   10.075895] brcmfmac: power management disabled
[   10.619270] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   10.619310] brcmfmac: power management disabled
[   11.377631] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   33.541778] random: crng init done
[   33.541789] random: 7 urandom warning(s) missed due to ratelimiting

**Comment by wyleu** [comment]
Seems to have cleared itself up with the release of #498
