### ISSUE TITLE
Feature request: Add alias for zynthian

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-sys#96]
It may be advantageous to provide an alias or soft link to allow a user to start zynthian from the terminal command line by typing

`zynthian`

rather than the need to type

`/zynthian/zynthian-ui/zynthian.sh`

**Comment by jofemodo** [comment]
Try "zynthian.sh" in a recently updated zynthian ;-)

**Comment by riban-bw** [comment]
Ah yes! Cheers!
